using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Simple.Objects
{
    #region |   Code Generated by Simple.Objects Code Generator   |

    partial class SortableSimpleObject
    {
        protected long previousId, oldPreviousId;
        protected int orderIndex, oldOrderIndex;

        #region |   Public Method Overrides   |

        public long PreviousId
        {
            get { return this.previousId; }
            protected internal set { base.SetPropertyValue(this.GetModel().PreviousIdPropertyModel, value); }
        }

        public int OrderIndex
        {
            get { return this.orderIndex; }
            set { base.SetPropertyValue(this.GetModel().OrderIndexPropertyModel, value); }
        }

        #endregion |   Public Method Overrides   |
    }

    #endregion |   Code Generated by Simple.Objects Code Generator   |
}
