//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;

//namespace Simple.Objects
//{
//	#region |   Code Generated by Simple.Objects Code Generator   |

//	partial class GroupMembershipElement
//	{
//		#region |   Protected Members   |

//		protected int relationKey, oldRelationKey;
//		protected int object1TableId, oldObject1TableId;
//		protected long object1Id, oldObject1Id;
//		protected int object2TableId, oldObject2TableId;
//		protected long object2Id, oldObject2Id;

//		#endregion |   Protected Members   |

//		#region |   Private Static Members   |

//		private static Func<GroupMembershipElement, object>[] GetFieldValueMethods;
//		private static Func<GroupMembershipElement, object>[] GetOldFieldValueMethods;
//		private static Action<GroupMembershipElement, object>[] SetFieldValueMethods;
//		private static Action<GroupMembershipElement, object>[] SetOldFieldValueMethods;

//		#endregion |   Private Static Members   |

//		#region |   Static Methods Initialization   |

//		static GroupMembershipElement()
//		{
//			int maxIndex = GroupMembershipElementModel.PropertyModel.GetCollection().GetMaxIndex();

//			GetFieldValueMethods = new Func<GroupMembershipElement, object>[maxIndex + 1];
//			GetFieldValueMethods[GroupMembershipElementModel.PropertyModel.Id.PropertyIndex] = (item) => item.id;
//			GetFieldValueMethods[GroupMembershipElementModel.PropertyModel.RelationKey.PropertyIndex] = (item) => item.relationKey;
//			GetFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object1TableId.PropertyIndex] = (item) => item.object1TableId;
//			GetFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object1Id.PropertyIndex] = (item) => item.object1Id;
//			GetFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object2TableId.PropertyIndex] = (item) => item.object2TableId;
//			GetFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object2Id.PropertyIndex] = (item) => item.object2Id;

//			GetOldFieldValueMethods = new Func<GroupMembershipElement, object>[maxIndex + 1];
//			GetOldFieldValueMethods[GroupMembershipElementModel.PropertyModel.Id.PropertyIndex] = (item) => item.oldId;
//			GetOldFieldValueMethods[GroupMembershipElementModel.PropertyModel.RelationKey.PropertyIndex] = (item) => item.oldRelationKey;
//			GetOldFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object1TableId.PropertyIndex] = (item) => item.oldObject1TableId;
//			GetOldFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object1Id.PropertyIndex] = (item) => item.oldObject1Id;
//			GetOldFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object2TableId.PropertyIndex] = (item) => item.oldObject2TableId;
//			GetOldFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object2Id.PropertyIndex] = (item) => item.oldObject2Id;

//			SetFieldValueMethods = new Action<GroupMembershipElement, object>[maxIndex + 1];
//			SetFieldValueMethods[GroupMembershipElementModel.PropertyModel.Id.PropertyIndex] = (item, value) => item.id = (long)value;
//			SetFieldValueMethods[GroupMembershipElementModel.PropertyModel.RelationKey.PropertyIndex] = (item, value) => item.relationKey = (int)value;
//			SetFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object1TableId.PropertyIndex] = (item, value) => item.object1TableId = (int)value;
//			SetFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object1Id.PropertyIndex] = (item, value) => item.object1Id = (long)value;
//			SetFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object2TableId.PropertyIndex] = (item, value) => item.object2TableId = (int)value;
//			SetFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object2Id.PropertyIndex] = (item, value) => item.object2Id = (long)value;

//			SetOldFieldValueMethods = new Action<GroupMembershipElement, object>[maxIndex + 1];
//			SetOldFieldValueMethods[GroupMembershipElementModel.PropertyModel.Id.PropertyIndex] = (item, value) => item.oldId = (long)value;
//			SetOldFieldValueMethods[GroupMembershipElementModel.PropertyModel.RelationKey.PropertyIndex] = (item, value) => item.oldRelationKey = (int)value;
//			SetOldFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object1TableId.PropertyIndex] = (item, value) => item.oldObject1TableId = (int)value;
//			SetOldFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object1Id.PropertyIndex] = (item, value) => item.oldObject1Id = (long)value;
//			SetOldFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object2TableId.PropertyIndex] = (item, value) => item.oldObject2TableId = (int)value;
//			SetOldFieldValueMethods[GroupMembershipElementModel.PropertyModel.Object2Id.PropertyIndex] = (item, value) => item.oldObject2Id = (long)value;
//		}

//		#endregion |   Static Methods Initialization   |

//		#region |   Properties by Object Property Model   |

//		/// <summary>
//		///  Gets or sets RelationKey property value.
//		/// </summary>
//		public int RelationKey
//		{
//			get { return this.relationKey; }
//			private set { this.SetPropertyValue<int>(GroupMembershipElementModel.PropertyModel.RelationKey, value, ref this.relationKey, this.oldRelationKey); }
//		}

//		/// <summary>
//		///  Gets or sets Object1TableId property value.
//		/// </summary>
//		internal int Object1TableId
//		{
//			get { return this.object1TableId; }
//			private set { this.SetPropertyValue<int>(GroupMembershipElementModel.PropertyModel.Object1TableId, value, ref this.object1TableId, this.oldObject1TableId); }
//		}

//		/// <summary>
//		///  Gets or sets Object1Id property value.
//		/// </summary>
//		internal long Object1Id
//		{
//			get { return this.object1Id; }
//			private set { this.SetPropertyValue<long>(GroupMembershipElementModel.PropertyModel.Object1Id, value, ref this.object1Id, this.oldObject1Id); }
//		}

//		/// <summary>
//		///  Gets or sets Object2TableId property value.
//		/// </summary>
//		internal int Object2TableId
//		{
//			get { return this.object2TableId; }
//			private set { this.SetPropertyValue<int>(GroupMembershipElementModel.PropertyModel.Object2TableId, value, ref this.object2TableId, this.oldObject2TableId); }
//		}

//		/// <summary>
//		///  Gets or sets Object2Id property value.
//		/// </summary>
//		internal long Object2Id
//		{
//			get { return this.object2Id; }
//			private set { this.SetPropertyValue<long>(GroupMembershipElementModel.PropertyModel.Object2Id, value, ref this.object2Id, this.oldObject2Id); }
//		}

//		#endregion |   Properties by Object Property Model   |

//		#region |   One-To-Many Relation Properties   |

//		/// <summary>
//		/// Gets one-to-many relation foreign GraphElements collection.
//		/// </summary>
//		public override SimpleObjectCollection<GraphElement> GraphElements
//		{
//			get { return this.GetOneToManyForeignObjectCollection<GraphElement>(RelationPolicyModelBase.OneToManyGraphElementToSimpleObject); }
//		}

//		#endregion |   One-To-Many Relation Properties   |

//		#region |   Public Method Overrids   |

//		/// <summary>
//		/// Gets the GroupMembershipElementModel definition instance.
//		/// </summary>
//		public override ISimpleObjectModel GetModel()
//		{
//			return GroupMembershipElementModel.Instance;
//		}

//		/// <summary>
//		/// Gets the one-to-many collection based on relation key. If no one-to-many relation specified in relation model for this object, the base class method is called.
//		/// </summary>
//		/// <param name="relationKey">The one-to-many relation key</param>
//		/// <returns>The <see cref="SimpleObjectCollection"/> result.</returns>
//		public override SimpleObjectCollection GetOneToManyForeignObjectCollection(int relationKey)
//		{
//			if (relationKey == RelationPolicyModelBase.OneToManyGraphElementToSimpleObject.RelationKey)
//				return this.GraphElements;

//			return base.GetOneToManyForeignObjectCollection(relationKey);
//		}

//		#endregion |   Public Method Overrids   |

//		#region |   Protected Abstract Methods Overrides  |

//		/// <summary>
//		/// Gets field property value by property index.
//		/// </summary>
//		protected override object GetFieldValue(int propertyIndex)
//		{
//			return GetFieldValueMethods[propertyIndex](this);
//		}

//		/// <summary>
//		/// Gets field old property value by property index.
//		/// </summary>
//		protected override object GetOldFieldValue(int propertyIndex)
//		{
//			return GetOldFieldValueMethods[propertyIndex](this);
//		}

//		/// <summary>
//		/// Sets field property value by property index.
//		/// </summary>
//		protected override void SetFieldValue(int propertyIndex, object value)
//		{
//			SetFieldValueMethods[propertyIndex](this, value);
//		}

//		/// <summary>
//		/// Sets field old property value by property index.
//		/// </summary>
//		protected override void SetOldFieldValue(int propertyIndex, object value)
//		{
//			SetOldFieldValueMethods[propertyIndex](this, value);
//		}

//		#endregion |   Protected Abstract Methods Overrides  |
//	}

//	#endregion |   Code Generated by Simple.Objects Code Generator   |
//}
