using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#nullable enable

namespace Simple.Objects
{
    #region |   Code Generated by Simple.Objects Code Generator   |

    partial class GroupMembership
    {
        #region |   Protected Members   |

        protected int relationKey, oldRelationKey;
        protected int object1TableId, oldObject1TableId;
        protected long object1Id, oldObject1Id;
        protected int object2TableId, oldObject2TableId;
        protected long object2Id, oldObject2Id;

        #endregion |   Protected Members   |

        #region |   Private Static Members   |

        private static Func<GroupMembership, object?>[] GetFieldValueMethods;
        private static Func<GroupMembership, object?>[] GetOldFieldValueMethods;
        private static Action<GroupMembership, object>[] SetFieldValueMethods;
        private static Action<GroupMembership, object>[] SetOldFieldValueMethods;

        #endregion |   Private Static Members   |

        #region |   Static Methods Initialization   |

        static GroupMembership()
        {
            int maxIndex = GroupMembershipModel.PropertyModel.GetCollection().GetMaxIndex();

            GetFieldValueMethods = new Func<GroupMembership, object?>[maxIndex + 1];
            GetFieldValueMethods[GroupMembershipModel.PropertyModel.Id.PropertyIndex]             = (item) => item.id;
            GetFieldValueMethods[GroupMembershipModel.PropertyModel.RelationKey.PropertyIndex]    = (item) => item.relationKey;
            GetFieldValueMethods[GroupMembershipModel.PropertyModel.Object1TableId.PropertyIndex] = (item) => item.object1TableId;
            GetFieldValueMethods[GroupMembershipModel.PropertyModel.Object1Id.PropertyIndex]      = (item) => item.object1Id;
            GetFieldValueMethods[GroupMembershipModel.PropertyModel.Object2TableId.PropertyIndex] = (item) => item.object2TableId;
            GetFieldValueMethods[GroupMembershipModel.PropertyModel.Object2Id.PropertyIndex]      = (item) => item.object2Id;

            GetOldFieldValueMethods = new Func<GroupMembership, object?>[maxIndex + 1];
            GetOldFieldValueMethods[GroupMembershipModel.PropertyModel.Id.PropertyIndex]             = (item) => item.oldId;
            GetOldFieldValueMethods[GroupMembershipModel.PropertyModel.RelationKey.PropertyIndex]    = (item) => item.oldRelationKey;
            GetOldFieldValueMethods[GroupMembershipModel.PropertyModel.Object1TableId.PropertyIndex] = (item) => item.oldObject1TableId;
            GetOldFieldValueMethods[GroupMembershipModel.PropertyModel.Object1Id.PropertyIndex]      = (item) => item.oldObject1Id;
            GetOldFieldValueMethods[GroupMembershipModel.PropertyModel.Object2TableId.PropertyIndex] = (item) => item.oldObject2TableId;
            GetOldFieldValueMethods[GroupMembershipModel.PropertyModel.Object2Id.PropertyIndex]      = (item) => item.oldObject2Id;

            SetFieldValueMethods = new Action<GroupMembership, object>[maxIndex + 1];
            SetFieldValueMethods[GroupMembershipModel.PropertyModel.Id.PropertyIndex]             = (item, value) => item.id = (long)value;
            SetFieldValueMethods[GroupMembershipModel.PropertyModel.RelationKey.PropertyIndex]    = (item, value) => item.relationKey = (int)value;
            SetFieldValueMethods[GroupMembershipModel.PropertyModel.Object1TableId.PropertyIndex] = (item, value) => item.object1TableId = (int)value;
            SetFieldValueMethods[GroupMembershipModel.PropertyModel.Object1Id.PropertyIndex]      = (item, value) => item.object1Id = (long)value;
            SetFieldValueMethods[GroupMembershipModel.PropertyModel.Object2TableId.PropertyIndex] = (item, value) => item.object2TableId = (int)value;
            SetFieldValueMethods[GroupMembershipModel.PropertyModel.Object2Id.PropertyIndex]      = (item, value) => item.object2Id = (long)value;

            SetOldFieldValueMethods = new Action<GroupMembership, object>[maxIndex + 1];
            SetOldFieldValueMethods[GroupMembershipModel.PropertyModel.Id.PropertyIndex]             = (item, value) => item.oldId = (long)value;
            SetOldFieldValueMethods[GroupMembershipModel.PropertyModel.RelationKey.PropertyIndex]    = (item, value) => item.oldRelationKey = (int)value;
            SetOldFieldValueMethods[GroupMembershipModel.PropertyModel.Object1TableId.PropertyIndex] = (item, value) => item.oldObject1TableId = (int)value;
            SetOldFieldValueMethods[GroupMembershipModel.PropertyModel.Object1Id.PropertyIndex]      = (item, value) => item.oldObject1Id = (long)value;
            SetOldFieldValueMethods[GroupMembershipModel.PropertyModel.Object2TableId.PropertyIndex] = (item, value) => item.oldObject2TableId = (int)value;
            SetOldFieldValueMethods[GroupMembershipModel.PropertyModel.Object2Id.PropertyIndex]      = (item, value) => item.oldObject2Id = (long)value;
        }

        #endregion |   Static Methods Initialization   |

        #region |   Properties by Object Property Model   |

        /// <summary>
        ///  Gets or sets RelationKey property value.
        /// </summary>
        public int RelationKey
        {
            get { return this.relationKey; }
            private set { this.SetPropertyValue(GroupMembershipModel.PropertyModel.RelationKey, value); }
		}

        /// <summary>
        ///  Gets or sets Object1TableId property value.
        /// </summary>
        internal int Object1TableId
        {
            get { return this.object1TableId; }
            private set { this.SetPropertyValue(GroupMembershipModel.PropertyModel.Object1TableId, value); }
		}

        /// <summary>
        ///  Gets or sets Object1Id property value.
        /// </summary>
        internal long Object1Id
        {
            get { return this.object1Id; }
            private set { this.SetPropertyValue(GroupMembershipModel.PropertyModel.Object1Id, value); }
		}

        /// <summary>
        ///  Gets or sets Object2TableId property value.
        /// </summary>
        internal int Object2TableId
        {
            get { return this.object2TableId; }
            private set { this.SetPropertyValue(GroupMembershipModel.PropertyModel.Object2TableId, value); }
		}

        /// <summary>
        ///  Gets or sets Object2Id property value.
        /// </summary>
        internal long Object2Id
        {
            get { return this.object2Id; }
            private set { this.SetPropertyValue(GroupMembershipModel.PropertyModel.Object2Id, value); }
		}

        #endregion |   Properties by Object Property Model   |

        #region |   One-To-Many Relation Properties   |

        /// <summary>
        /// Gets one-to-many relation foreign GraphElements collection.
        /// </summary>
        public override SimpleObjectCollection<GraphElement> GraphElements
        {
            get { return this.GetOneToManyForeignObjectCollection<GraphElement>(RelationPolicyModelBase.OneToManyGraphElementToSimpleObject); }
        }

        #endregion |   One-To-Many Relation Properties   |

        #region |   Public Overriden Methods   |

        /// <summary>
        /// Gets the GroupMembershipModel definition instance.
        /// </summary>
        public override ISimpleObjectModel GetModel()
        {
            return GroupMembershipModel.Instance; 
        }

        /// <summary>
        /// Gets the one-to-many collection based on relation key. If no one-to-many relation specified in relation model for this object, the base class method is called.
        /// </summary>
        /// <param name="relationKey">The one-to-many relation key</param>
        /// <returns>The <see cref="SimpleObjectCollection?"/> result.</returns>
        public override SimpleObjectCollection? GetOneToManyForeignObjectCollection(int relationKey)
        {
            if (relationKey == RelationPolicyModelBase.OneToManyGraphElementToSimpleObject.RelationKey)
                return this.GraphElements;

            return base.GetOneToManyForeignObjectCollection(relationKey);
        }

        #endregion |   Public Overriden Methods   |

        #region |   Protected Abstract Overriden Methods  |

        /// <summary>
        /// Gets field property value by property index.
        /// </summary>
        protected override object? GetFieldValue(int propertyIndex)
        {
            return GetFieldValueMethods[propertyIndex](this);
        }

        /// <summary>
        /// Gets field old property value by property index.
        /// </summary>
        protected override object? GetOldFieldValue(int propertyIndex)
        {
            return GetOldFieldValueMethods[propertyIndex](this);
        }

        /// <summary>
        /// Sets field property value by property index.
        /// </summary>
        protected override void SetFieldValue(int propertyIndex, object value)
        {
            SetFieldValueMethods[propertyIndex](this, value);
        }

        /// <summary>
        /// Sets field old property value by property index.
        /// </summary>
        protected override void SetOldFieldValue(int propertyIndex, object value)
        {
            SetOldFieldValueMethods[propertyIndex](this, value);
        }

        #endregion |   Protected Abstract Overriden Methods  |
    }

    #endregion |   Code Generated by Simple.Objects Code Generator   |
}
