//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;

//namespace Simple.Objects
//{
//    #region |   Code Generated by Simple.Objects Code Generator   |

//    partial class User
//    {
//        #region |   Protected Members   |

//        protected string description, oldDescription;
//        protected string firstName, oldFirstName;
//        protected string lastName, oldLastName;
//        protected string username, oldUsername;
//        protected string password, oldPassword;
//        protected string location, oldLocation;
//        protected bool enabled, oldEnabled;

//        #endregion |   Protected Members   |

//        #region |   Private Static Members   |

//        private static Func<User, object>[] GetFieldValueMethods;
//        private static Func<User, object>[] GetOldFieldValueMethods;
//        private static Action<User, object>[] SetFieldValueMethods;
//        private static Action<User, object>[] SetOldFieldValueMethods;

//        #endregion |   Private Static Members   |

//        #region |   Static Methods Initialization   |

//        static User()
//        {
//            int maxIndex = UserModel.PropertyModel.GetCollection().GetMaxIndex();

//            GetFieldValueMethods = new Func<User, object>[maxIndex + 1];
//            GetFieldValueMethods[UserModel.PropertyModel.Id.Index]          = (item) => item.id;
//            GetFieldValueMethods[UserModel.PropertyModel.Description.Index] = (item) => item.description;
//            GetFieldValueMethods[UserModel.PropertyModel.FirstName.Index]   = (item) => item.firstName;
//            GetFieldValueMethods[UserModel.PropertyModel.LastName.Index]    = (item) => item.lastName;
//            GetFieldValueMethods[UserModel.PropertyModel.Username.Index]    = (item) => item.username;
//            GetFieldValueMethods[UserModel.PropertyModel.Password.Index]    = (item) => item.password;
//            GetFieldValueMethods[UserModel.PropertyModel.Location.Index]    = (item) => item.location;
//            GetFieldValueMethods[UserModel.PropertyModel.Enabled.Index]     = (item) => item.enabled;

//            GetOldFieldValueMethods = new Func<User, object>[maxIndex + 1];
//            GetOldFieldValueMethods[UserModel.PropertyModel.Id.Index]          = (item) => item.oldId;
//            GetOldFieldValueMethods[UserModel.PropertyModel.Description.Index] = (item) => item.oldDescription;
//            GetOldFieldValueMethods[UserModel.PropertyModel.FirstName.Index]   = (item) => item.oldFirstName;
//            GetOldFieldValueMethods[UserModel.PropertyModel.LastName.Index]    = (item) => item.oldLastName;
//            GetOldFieldValueMethods[UserModel.PropertyModel.Username.Index]    = (item) => item.oldUsername;
//            GetOldFieldValueMethods[UserModel.PropertyModel.Password.Index]    = (item) => item.oldPassword;
//            GetOldFieldValueMethods[UserModel.PropertyModel.Location.Index]    = (item) => item.oldLocation;
//            GetOldFieldValueMethods[UserModel.PropertyModel.Enabled.Index]     = (item) => item.oldEnabled;

//            SetFieldValueMethods = new Action<User, object>[maxIndex + 1];
//            SetFieldValueMethods[UserModel.PropertyModel.Id.Index]          = (item, value) => item.id = (long)value;
//            SetFieldValueMethods[UserModel.PropertyModel.Description.Index] = (item, value) => item.description = (string)value;
//            SetFieldValueMethods[UserModel.PropertyModel.FirstName.Index]   = (item, value) => item.firstName = (string)value;
//            SetFieldValueMethods[UserModel.PropertyModel.LastName.Index]    = (item, value) => item.lastName = (string)value;
//            SetFieldValueMethods[UserModel.PropertyModel.Username.Index]    = (item, value) => item.username = (string)value;
//            SetFieldValueMethods[UserModel.PropertyModel.Password.Index]    = (item, value) => item.password = (string)value;
//            SetFieldValueMethods[UserModel.PropertyModel.Location.Index]    = (item, value) => item.location = (string)value;
//            SetFieldValueMethods[UserModel.PropertyModel.Enabled.Index]     = (item, value) => item.enabled = (bool)value;

//            SetOldFieldValueMethods = new Action<User, object>[maxIndex + 1];
//            SetOldFieldValueMethods[UserModel.PropertyModel.Id.Index]          = (item, value) => item.oldId = (long)value;
//            SetOldFieldValueMethods[UserModel.PropertyModel.Description.Index] = (item, value) => item.oldDescription = (string)value;
//            SetOldFieldValueMethods[UserModel.PropertyModel.FirstName.Index]   = (item, value) => item.oldFirstName = (string)value;
//            SetOldFieldValueMethods[UserModel.PropertyModel.LastName.Index]    = (item, value) => item.oldLastName = (string)value;
//            SetOldFieldValueMethods[UserModel.PropertyModel.Username.Index]    = (item, value) => item.oldUsername = (string)value;
//            SetOldFieldValueMethods[UserModel.PropertyModel.Password.Index]    = (item, value) => item.oldPassword = (string)value;
//            SetOldFieldValueMethods[UserModel.PropertyModel.Location.Index]    = (item, value) => item.oldLocation = (string)value;
//            SetOldFieldValueMethods[UserModel.PropertyModel.Enabled.Index]     = (item, value) => item.oldEnabled = (bool)value;
//        }

//        #endregion |   Static Methods Initialization   |

//        #region |   Properties by Object Property Model   |

//        /// <summary>
//        ///  Gets or sets Description property value.
//        /// </summary>
//        public string Description
//        {
//            get { return this.description; }
//            set { base.SetPropertyValue<string>(UserModel.PropertyModel.Description, value, ref this.description, this.oldDescription); }
//		}

//        /// <summary>
//        ///  Gets or sets FirstName property value.
//        /// </summary>
//        public string FirstName
//        {
//            get { return this.firstName; }
//            set { base.SetPropertyValue<string>(UserModel.PropertyModel.FirstName, value, ref this.firstName, this.oldFirstName); }
//		}

//        /// <summary>
//        ///  Gets or sets LastName property value.
//        /// </summary>
//        public string LastName
//        {
//            get { return this.lastName; }
//            set { base.SetPropertyValue<string>(UserModel.PropertyModel.LastName, value, ref this.lastName, this.oldLastName); }
//		}

//        /// <summary>
//        ///  Gets or sets Username property value.
//        /// </summary>
//        public string Username
//        {
//            get { return this.username; }
//            set { base.SetPropertyValue<string>(UserModel.PropertyModel.Username, value, ref this.username, this.oldUsername); }
//		}

//        /// <summary>
//        ///  Gets or sets Password property value.
//        /// </summary>
//        public string Password
//        {
//            get { return this.password; }
//            set { base.SetPropertyValue<string>(UserModel.PropertyModel.Password, value, ref this.password, this.oldPassword); }
//		}

//        /// <summary>
//        ///  Gets or sets Location property value.
//        /// </summary>
//        public string Location
//        {
//            get { return this.location; }
//            set { base.SetPropertyValue<string>(UserModel.PropertyModel.Location, value, ref this.location, this.oldLocation); }
//		}

//        /// <summary>
//        ///  Gets or sets Enabled property value.
//        /// </summary>
//        public bool Enabled
//        {
//            get { return this.enabled; }
//            set { base.SetPropertyValue<bool>(UserModel.PropertyModel.Enabled, value, ref this.enabled, this.oldEnabled); }
//		}

//        #endregion |   Properties by Object Property Model   |

//        #region |   Public Overriden Methods   |

//        /// <summary>
//        /// Gets the UserModel definition instance.
//        /// </summary>
//        public override ISimpleObjectModel GetModel()
//        {
//            return UserModel.Instance; 
//        }

//        #endregion |   Public Overriden Methods   |

//        #region |   Protected Overriden Abstract Methods   |

//        /// <summary>
//        /// Gets field property value by property index.
//        /// </summary>
//        protected override object GetFieldValue(int propertyIndex)
//        {
//            return GetFieldValueMethods[propertyIndex](this);
//        }

//        /// <summary>
//        /// Gets field old property value by property index.
//        /// </summary>
//        protected override object GetOldFieldValue(int propertyIndex)
//        {
//            return GetOldFieldValueMethods[propertyIndex](this);
//        }

//        /// <summary>
//        /// Sets field property value by property index.
//        /// </summary>
//        protected override void SetFieldValue(int propertyIndex, object value)
//        {
//            SetFieldValueMethods[propertyIndex](this, value);
//        }

//        /// <summary>
//        /// Sets field old property value by property index.
//        /// </summary>
//        protected override void SetOldFieldValue(int propertyIndex, object value)
//        {
//            SetOldFieldValueMethods[propertyIndex](this, value);
//        }

//        #endregion |   Protected Overriden Abstract Methods   |
//    }

//    #endregion |   Code Generated by Simple.Objects Code Generator   |
//}
