//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;

//namespace Simple.Objects
//{
//    #region |   Code Generated by Simple.Objects Code Generator   |

//    partial class Graph
//    {
//        #region |   Protected Members   |

//        protected int graphKey, oldGraphKey;
//        protected string name, oldName;

//        #endregion |   Protected Members   |

//        #region |   Private Static Members   |

//        private static Func<Graph, object>[] GetFieldValueMethods;
//        private static Func<Graph, object>[] GetOldFieldValueMethods;
//        private static Action<Graph, object>[] SetFieldValueMethods;
//        private static Action<Graph, object>[] SetOldFieldValueMethods;

//        #endregion |   Private Static Members   |

//        #region |   Static Methods Initialization   |

//        static Graph()
//        {
//            int maxIndex = GraphModel.PropertyModel.GetCollection().GetMaxIndex();

//            GetFieldValueMethods = new Func<Graph, object>[maxIndex + 1];
//            GetFieldValueMethods[GraphModel.PropertyModel.Id.Index]       = (item) => item.id;
//            GetFieldValueMethods[GraphModel.PropertyModel.GraphKey.Index] = (item) => item.graphKey;
//            GetFieldValueMethods[GraphModel.PropertyModel.Name.Index]     = (item) => item.name;

//            GetOldFieldValueMethods = new Func<Graph, object>[maxIndex + 1];
//            GetOldFieldValueMethods[GraphModel.PropertyModel.Id.Index]       = (item) => item.oldId;
//            GetOldFieldValueMethods[GraphModel.PropertyModel.GraphKey.Index] = (item) => item.oldGraphKey;
//            GetOldFieldValueMethods[GraphModel.PropertyModel.Name.Index]     = (item) => item.oldName;

//            SetFieldValueMethods = new Action<Graph, object>[maxIndex + 1];
//            SetFieldValueMethods[GraphModel.PropertyModel.Id.Index]       = (item, value) => item.id = (long)value;
//            SetFieldValueMethods[GraphModel.PropertyModel.GraphKey.Index] = (item, value) => item.graphKey = (int)value;
//            SetFieldValueMethods[GraphModel.PropertyModel.Name.Index]     = (item, value) => item.name = (string)value;

//            SetOldFieldValueMethods = new Action<Graph, object>[maxIndex + 1];
//            SetOldFieldValueMethods[GraphModel.PropertyModel.Id.Index]       = (item, value) => item.oldId = (long)value;
//            SetOldFieldValueMethods[GraphModel.PropertyModel.GraphKey.Index] = (item, value) => item.oldGraphKey = (int)value;
//            SetOldFieldValueMethods[GraphModel.PropertyModel.Name.Index]     = (item, value) => item.oldName = (string)value;
//        }

//        #endregion |   Static Methods Initialization   |

//        #region |   Properties by Object Property Model   |

//        /// <summary>
//        ///  Gets or sets GraphKey property value.
//        /// </summary>
//        public int GraphKey
//        {
//            get { return this.graphKey; }
//            set { this.SetPropertyValue<int>(GraphModel.PropertyModel.GraphKey, value, ref this.graphKey, this.oldGraphKey); }
//		}

//        /// <summary>
//        ///  Gets or sets Name property value.
//        /// </summary>
//        public string Name
//        {
//            get { return this.name; }
//            set { this.SetPropertyValue<string>(GraphModel.PropertyModel.Name, value, ref this.name, this.oldName); }
//		}

//        #endregion |   Properties by Object Property Model   |

//        #region |   One-To-Many Relation Properties   |

//        /// <summary>
//        /// Gets one-to-many relation foreign AllGraphElements collection.
//        /// </summary>
//        public SimpleObjectCollection<GraphElement> AllGraphElements
//        {
//            get { return this.GetOneToManyForeignObjectCollection<GraphElement>(RelationPolicyModelBase.OneToManyGraphToGraphElement); }
//        }

//        /// <summary>
//        /// Gets one-to-many relation foreign GraphElements collection.
//        /// </summary>
//        public override SimpleObjectCollection<GraphElement> GraphElements
//        {
//            get { return this.GetOneToManyForeignObjectCollection<GraphElement>(RelationPolicyModelBase.OneToManyGraphElementToSimpleObject); }
//        }

//        #endregion |   One-To-Many Relation Properties   |

//        #region |   Public Method Overrids   |

//        /// <summary>
//        /// Gets the GraphModel definition instance.
//        /// </summary>
//        public override ISimpleObjectModel GetModel()
//        {
//            return GraphModel.Instance; 
//        }

//        /// <summary>
//        /// Gets the one-to-many collection based on relation key. If no one-to-many relation specified in relation model for this object, the base class method is called.
//        /// </summary>
//        /// <param name="relationKey">The one-to-many relation key</param>
//        /// <returns>The <see cref="ISimpleObjectCollection"/> value.</returns>
//        public override ISimpleObjectCollection GetOneToManyForeignObjectCollection(int relationKey)
//        {
//            if (relationKey == RelationPolicyModelBase.OneToManyGraphToGraphElement.RelationKey)
//                return this.AllGraphElements;
//            else if (relationKey == RelationPolicyModelBase.OneToManyGraphElementToSimpleObject.RelationKey)
//                return this.GraphElements;

//            return base.GetOneToManyForeignObjectCollection(relationKey);
//        }

//        #endregion |   Public Method Overrids   |

//        #region |   Protected Abstract Methods Overrides  |

//        /// <summary>
//        /// Gets field property value by property index.
//        /// </summary>
//        protected override object GetFieldValue(int propertyIndex)
//        {
//            return GetFieldValueMethods[propertyIndex](this);
//        }

//        /// <summary>
//        /// Gets field old property value by property index.
//        /// </summary>
//        protected override object GetOldFieldValue(int propertyIndex)
//        {
//            return GetOldFieldValueMethods[propertyIndex](this);
//        }

//        /// <summary>
//        /// Sets field property value by property index.
//        /// </summary>
//        protected override void SetFieldValue(int propertyIndex, object value)
//        {
//            SetFieldValueMethods[propertyIndex](this, value);
//        }

//        /// <summary>
//        /// Sets field old property value by property index.
//        /// </summary>
//        protected override void SetOldFieldValue(int propertyIndex, object value)
//        {
//            SetOldFieldValueMethods[propertyIndex](this, value);
//        }

//        #endregion |   Protected Abstract Methods Overrides  |
//    }

//    #endregion |   Code Generated by Simple.Objects Code Generator   |
//}
